theme: jekyll-theme-cayman
url: 'https://apollner.github.io/'

baseurl: 'https://apollner.github.io/'

theme: jekyll-theme-hacker
markdown: GFM
description: Bookmark this to keep an eye on my project updates!
